### ISSUE TITLE
Abrir el código de Como Llego

### ISSUE THREAD

**Issue by juandopazo** [gcba/BADistro#1]
Sería muy útil que "Cómo Llego?" sea open source. Es una de las aplicaciones más utiles del GCBA y creo que se beneficiaría de las ocasionales pull requests.

@mativs :P

**Comment by impronunciable** [comment]
+1

**Comment by abadfederico** [comment]
+1  🚌

**Comment by peorth80** [comment]
+1

**Comment by davo** [comment]
+1

**Comment by jazzido** [comment]
+1

**Comment by nameghino** [comment]
+1

**Comment by peorth80** [comment]
+1

**Comment by ignacioricci** [comment]
+1

**Comment by avilaton** [comment]
+1

**Comment by dabadie** [comment]
Vamos a liberar el codigo aca https://github.com/gcba/BA-Como-Llego donde van a poder colaborar.

**Comment by impronunciable** [comment]
Iuju!

**Comment by maza23** [comment]
Cuando?

**Comment by walbuc** [comment]
+1. Seria ideal que mapas también sea open source. Otras ciudades se podrían beneficiar.

**Comment by juandopazo** [comment]
Iupi! \o/
