### ISSUE TITLE
Problemas 

### ISSUE THREAD

**Issue by mariaclorinda** [gcba/BADistro#10]

**Comment by fcastagnino** [comment]
Hola María,

Te pido si nos podés algún  detalle del error para poder ayudarte.

Saludos

**Comment by mariaclorinda** [comment]
Hola Florencia,
Muchas gracias por tu respuesta.Te cuento que tengo un servidor debian 8, Apache, PostgreSQL, PHP y Drush instalados. Un sitio Drupal Recien instalado en /var/www/html/mi_sitio. Hasta ahi voy bien, me descargue el perfil badistro y lo coloque en /var/www/html. El problema es que al ejecutar el comando "sh scripts/build.sh var/www/html/mi_sitio" la unica opcion que me da es removerlo. Capaz yo este haciendo algo mal. Saludos
