### ISSUE TITLE
Instalacion Sin ssh

### ISSUE THREAD

**Issue by matudelatower** [gcba/BADistro#7]
Habría posibilidad e instalarlo sin tener acceso ssh al servidor?

Intenté hacer el deploy en mi maquina local, y subirlo comprimido pero e instalarlo arriba, pero me tira internal server error.

Lastimosamente la modernización no es tan amiga de la burocracia...

**Comment by eduvila** [comment]
Podés instalar drush en tu maquina local, seguir la instalación (sh scripts/build.sh)  y subir por ftp al hosting el directorio de la instalación.

**Comment by matudelatower** [comment]
Si eso hice, pero en el server tira error 500.

**Comment by matudelatower** [comment]
Perdón, ya lo solucioné. Era error mío.-
